name: Monthly issue metrics (Multi Repo)
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:
      - name: Get dates for last month
        shell: bash
        run: |
          # Calculate the first day of the previous month
          first_day=$(date -d "last month" +%Y-%m-01)

          # Calculate the last day of the previous month
          last_day=$(date -d "$first_day +1 month -1 day" +%Y-%m-%d)

          # Calculate the last day of the previous month
          today=$(date +%Y-%m-%d)

          #Set an environment variable with the date range
          echo "$first_day..$today"
          echo "last_month=$first_day..$today" >> "$GITHUB_ENV"

      - name: Get issue metrics
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:arsheshadri/edw repo:arsheshadri/gh_metrics is:pr created:${{ env.last_month }} -reason:"not planned"'

#      - name: Print GitHub event payload
#        run: echo "${{ toJson(github.event) }}"

      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Monthly issue metrics report (dev)
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./issue_metrics.md
          assignees: arsheshadri
