name: Github Events Utility
on:
  workflow_dispatch:

jobs:
  check_events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install PyGithub
        pip install snowflake-connector-python

    - name: Run Python script
      #run: python scripts/gh_metrics.py
      run: python scripts/github_events.py 
      env:
        GITHUB_ORG_NAME: "arsheshadri"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: config/configs.json
        
