name: Pull Request Monitor
on:
  pull_request:
    types: 
      - opened
      - reopened
      - closed

permissions:
  contents: read
jobs:
  monitor-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

- name: Print Pull Request Info
  run: |
    echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    echo "GITHUB_EVENT_NUMBER: $GITHUB_EVENT_NUMBER"
    echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
    echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
    jq -n --arg repo "$GITHUB_REPOSITORY" \
          --arg pr_num "$GITHUB_EVENT_NUMBER" \
          --arg incoming_branch "$GITHUB_HEAD_REF" \
          --arg target_branch "$GITHUB_BASE_REF" \
          '{"Repository": $repo, "PR_Number": $pr_num | tonumber, "Incoming_Branch": $incoming_branch, "Target_Branch": $target_branch}'    
